[package]
name = "bevy_contrib_bobox"
version = "0.1.0"
authors = ["Boris Boutillier <boris.boutillier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
rapier2d = [ "bevy_rapier2d"]

[dependencies]
bevy = "0.2.1"
bevy_rapier2d = { git = "https://github.com/Bobox214/bevy_rapier" , branch="rapier_configuration" , optional=true}